export const mdsData = [
  {
    mds_no: "MDS-2025-014",
    block: "Block-A1",
    deveui: "2CF7F120634001AA",
    lora_state: "Online",
    version: "V4.3.2",
    speed: "12",
    lora_no: "14",
    old_lora_no: "12",
    auto_clean: "Enabled",
    last_status: "Cleaning in Progress",
    battery_voltage: "24.6V",
    temperature: "38°C",
    site_id: "solar_farm_alhabad",
    company: "Taypro Robotics Pvt. Ltd.",
    manufactured_date: "2024-09-18",
    dock: "Dock-Left",
    rssi: "-89 dBm",
    snr: "7.4 dB",
    last_gateway: "Gateway-03",
    last_uplink: "2025-10-14 10:42:25",
    motor1_current: "3.2A",
    motor2_current: "3.5A",
    activate: "Yes",
    last_motor_update: "2025-10-14 10:41:30",
    no_of_rows: 5,

    // Rows structure with cleaning status and robot positions
    rows: [
      { row_no: 1, row_length: 20 },
      { row_no: 2, row_length: 22 },
      { row_no: 3, row_length: 23 },
      { row_no: 4, row_length: 24 },
      { row_no: 5, row_length: 25 },
    ],

    // Robot details with cleaning info
    robot: {
      robot_no: "Robot-13-V4",
      deveui: "2CF7F120634001AA",
      _id: "6710A4F2B1239AF9D0E2",
      block: "Block-A1",
      lora_no: "14",
      old_lora: "12",
      lora_state: "Online",
      last_uplink: "2025-10-14 10:42:25",
      site_id: "solar_farm_alhabad",
      current_row: 2,
      position: 12, // current horizontal position
      direction: 1, // 1 = forward, -1 = backward
      speed: "1.2 m/s",
      cleaning: true,
      battery_voltage: "24.6V",
      temperature: "38°C",
      last_activity: [
        {
          time: "2025-10-14 10:42:25",
          event: "Cleaning Started",
          row_no: 1,
          description: "Robot started cleaning Row 1",
        },
      ],
    },

    last_location: "Row 2 - Mid Section",
    current_location: "Row 2 - Near Dock",
  },
];

export const mdsTracking = [
  {
    mds_no: "MDS-2025-014",
    block: "Block-A1",
    deveui: "2CF7F120634001AA",
    site_id: "solar_farm_alhabad",
    company: "Taypro Robotics Pvt. Ltd.",

    no_of_rows: 5,
    default_mds_position: {
      mds_released: true,
      mds_released_at: "2025-10-13T10:49:40.841Z",
      mds_returned: true,
      mds_returned_at: "2025-10-13T10:49:40.841Z",
    },

    // ✅ NEW MDS position tracking (array form)
    mds_positions: [
      {
        row_number: 1,
        reached_at: "2025-10-13T10:49:40.841Z", // when MDS reached this row
        robot_released: true, // robot deployed from MDS
        robot_released_at: "2025-10-13T10:49:40.841Z",
        robot_returned: true, // robot not back yet
        robot_returned_at: "2025-10-13T10:49:40.841Z",
        cleaning_direction: "reverse", // forward | reverse
        active: false, // is MDS currently positioned here
      },
      {
        row_number: 2,
        reached_at: "2025-10-13T10:53:12.000Z",
        robot_released: true,
        robot_released_at: "2025-10-13T10:53:12.000Z",
        robot_returned: true,
        robot_returned_at: null,
        cleaning_direction: "reverse",
        active: false, // MDS currently here
      },
      {
        row_number: 3,
        reached_at: "2025-10-13T10:53:12.000Z",
        robot_released: true,
        robot_released_at: "2025-10-13T10:53:12.000Z",
        robot_returned: true,
        robot_returned_at: null,
        cleaning_direction: "reverse",
        active: false, // MDS currently here
      },
      {
        row_number: 4,
        reached_at: "2025-10-13T10:53:12.000Z",
        robot_released: true,
        robot_released_at: "2025-10-13T10:53:12.000Z",
        robot_returned: true,
        robot_returned_at: null,
        cleaning_direction: "reverse",
        active: false, // MDS currently here
      },
      {
        row_number: 5,
        reached_at: "2025-10-13T10:53:12.000Z",
        robot_released: true,
        robot_released_at: "2025-10-13T10:53:12.000Z",
        robot_returned: true,
        robot_returned_at: null,
        cleaning_direction: "reverse",
        active: false, // MDS currently here
      },
    ],

    // Rows structure with cleaning status and robot positions
    rows: [
      {
        row_no: 1,
        row_length: 80,
        cleaning: {
          start: true,
          startAt: "2025-10-13T10:48:40.789Z",
          finish: true,
          finishAt: null,
          cleaning_cancelled: false,
          cleaning_cancelled_at: null,
          battery_dead: false,
          battery_dead_at: null,
          battery_health_status: "✅ Battery is healthy!",
          battery_health_status_updated_at: "2025-10-13T10:53:40.800Z",
          forward_cleaning_time: null,
          forward_cleaning_time_received_at: null,
          reverse_cleaning_time: null,
          reverse_cleaning_time_received_at: null,
          total_cleaning_time: null,
          total_cleaning_time_received_at: null,
          battery_before_cleaning: null,
          battery_before_cleaning_received_at: null,
          battery_at_reverse_station: null,
          battery_at_reverse_station_received_at: null,
          battery_after_cleaning: null,
          battery_after_cleaning_received_at: null,
          temperature_before_cleaning: null,
          temperature_before_cleaning_received_at: null,
          temperature_at_reverse_station: null,
          temperature_at_reverse_station_received_at: null,
          temperature_after_cleaning: null,
          temperature_after_cleaning_received_at: null,
          cycle_average_brush_current: null,
          cycle_average_brush_current_received_at: null,
          cycle_average_wheel_current: null,
          cycle_average_wheel_current_received_at: null,
          cycle_max_wheel_current: null,
          cycle_max_wheel_current_received_at: null,
          cycle_max_brush_current: null,
          cycle_max_brush_current_received_at: null,
          cycle_count: null,
          cycle_count_received_at: null,
          cleaning_mertic: false,
          cleaning_metric_recievet_at: null,
        },
        track_details: [
          {
            point: 20,
            timestamp: "2025-10-13T10:49:10.824Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 21,
            timestamp: "2025-10-13T10:49:40.841Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 22,
            timestamp: "2025-10-13T10:50:22.810Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 23,
            timestamp: "2025-10-13T10:50:52.881Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 24,
            timestamp: "2025-10-13T10:51:22.843Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 25,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
        ],
        last_activity: [
          {
            timestamp: "2025-10-13T10:51:40.996Z",
            data: "19",
            topic: "Uplink Received",
            details:
              "19 uplink received from robot and robot is ready to clean",
          },
        ],
      },
      {
        row_no: 2,
        row_length: 102,
        cleaning: {
          start: true,
          startAt: "2025-10-13T10:48:40.789Z",
          finish: true,
          finishAt: "2025-10-13T10:48:40.789Z",
          cleaning_cancelled: false,
          cleaning_cancelled_at: null,
          battery_dead: false,
          battery_dead_at: null,
          battery_health_status: "✅ Battery is healthy!",
          battery_health_status_updated_at: "2025-10-13T10:53:40.800Z",
          forward_cleaning_time: null,
          forward_cleaning_time_received_at: null,
          reverse_cleaning_time: null,
          reverse_cleaning_time_received_at: null,
          total_cleaning_time: null,
          total_cleaning_time_received_at: null,
          battery_before_cleaning: null,
          battery_before_cleaning_received_at: null,
          battery_at_reverse_station: null,
          battery_at_reverse_station_received_at: null,
          battery_after_cleaning: null,
          battery_after_cleaning_received_at: null,
          temperature_before_cleaning: null,
          temperature_before_cleaning_received_at: null,
          temperature_at_reverse_station: null,
          temperature_at_reverse_station_received_at: null,
          temperature_after_cleaning: null,
          temperature_after_cleaning_received_at: null,
          cycle_average_brush_current: null,
          cycle_average_brush_current_received_at: null,
          cycle_average_wheel_current: null,
          cycle_average_wheel_current_received_at: null,
          cycle_max_wheel_current: null,
          cycle_max_wheel_current_received_at: null,
          cycle_max_brush_current: null,
          cycle_max_brush_current_received_at: null,
          cycle_count: null,
          cycle_count_received_at: null,
          cleaning_mertic: false,
          cleaning_metric_recievet_at: null,
        },
        track_details: [
          {
            point: 20,
            timestamp: "2025-10-13T10:49:10.824Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 21,
            timestamp: "2025-10-13T10:49:40.841Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 22,
            timestamp: "2025-10-13T10:50:22.810Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 23,
            timestamp: "2025-10-13T10:50:52.881Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 24,
            timestamp: "2025-10-13T10:51:22.843Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 25,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 26,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 27,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 28,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 29,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 30,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 31,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 32,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 33,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 34,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 35,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 36,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 37,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 38,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 39,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 40,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
        ],
        last_activity: [
          {
            timestamp: "2025-10-13T10:51:40.996Z",
            data: "19",
            topic: "Uplink Received",
            details:
              "19 uplink received from robot and robot is ready to clean",
          },
        ],
      },
    ],

    // Robot details with cleaning info
    robot: {
      robot_no: "Robot-13-V4",
      deveui: "2CF7F120634001AA",
      _id: "6710A4F2B1239AF9D0E2",
      block: "Block-A1",
      lora_no: "14",
      old_lora: "12",
      site_id: "solar_farm_alhabad",
    },
  },
  {
    mds_no: "MDS-2025-014",
    block: "Block-A1",
    deveui: "2CF7F120634001AA",
    site_id: "solar_farm_alhabad",
    company: "Taypro Robotics Pvt. Ltd.",
    no_of_rows: 2,
    default_mds_position: {
      mds_released: true,
      mds_released_at: "2025-10-13T10:49:40.841Z",
      mds_returned: true,
      mds_returned_at: null,
    },
    // ✅ NEW MDS position tracking (array form)
    mds_positions: [
      {
        row_number: 1,
        reached_at: "2025-10-13T10:49:40.841Z", // when MDS reached this row
        robot_released: true, // robot deployed from MDS
        robot_released_at: "2025-10-13T10:49:40.841Z",
        robot_returned: true, // robot not back yet
        robot_returned_at: "2025-10-13T10:49:40.841Z",
        cleaning_direction: "reverse", // forward | reverse
        active: false, // is MDS currently positioned here
      },
      {
        row_number: 2,
        reached_at: "2025-10-13T10:53:12.000Z",
        robot_released: true,
        robot_released_at: "2025-10-13T10:53:12.000Z",
        robot_returned: true,
        robot_returned_at: null,
        cleaning_direction: "reverse",
        active: false, // MDS currently here
      },
    ],

    // Rows structure with cleaning status and robot positions
    rows: [
      {
        row_no: 1,
        row_length: 120,
        cleaning: {
          start: true,
          startAt: "2025-10-13T10:48:40.789Z",
          finish: true,
          finishAt: null,
          cleaning_cancelled: false,
          cleaning_cancelled_at: null,
          battery_dead: false,
          battery_dead_at: null,
          battery_health_status: "✅ Battery is healthy!",
          battery_health_status_updated_at: "2025-10-13T10:53:40.800Z",
          forward_cleaning_time: null,
          forward_cleaning_time_received_at: null,
          reverse_cleaning_time: null,
          reverse_cleaning_time_received_at: null,
          total_cleaning_time: null,
          total_cleaning_time_received_at: null,
          battery_before_cleaning: null,
          battery_before_cleaning_received_at: null,
          battery_at_reverse_station: null,
          battery_at_reverse_station_received_at: null,
          battery_after_cleaning: null,
          battery_after_cleaning_received_at: null,
          temperature_before_cleaning: null,
          temperature_before_cleaning_received_at: null,
          temperature_at_reverse_station: null,
          temperature_at_reverse_station_received_at: null,
          temperature_after_cleaning: null,
          temperature_after_cleaning_received_at: null,
          cycle_average_brush_current: null,
          cycle_average_brush_current_received_at: null,
          cycle_average_wheel_current: null,
          cycle_average_wheel_current_received_at: null,
          cycle_max_wheel_current: null,
          cycle_max_wheel_current_received_at: null,
          cycle_max_brush_current: null,
          cycle_max_brush_current_received_at: null,
          cycle_count: null,
          cycle_count_received_at: null,
          cleaning_mertic: false,
          cleaning_metric_recievet_at: null,
        },
        track_details: [
          {
            point: 20,
            timestamp: "2025-10-13T10:49:10.824Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 21,
            timestamp: "2025-10-13T10:49:40.841Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 22,
            timestamp: "2025-10-13T10:50:22.810Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 23,
            timestamp: "2025-10-13T10:50:52.881Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 24,
            timestamp: "2025-10-13T10:51:22.843Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 25,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
        ],
        last_activity: [
          {
            timestamp: "2025-10-13T10:51:40.996Z",
            data: "19",
            topic: "Uplink Received",
            details:
              "19 uplink received from robot and robot is ready to clean",
          },
        ],
      },
      {
        row_no: 2,
        row_length: 152,
        cleaning: {
          start: true,
          startAt: "2025-10-13T10:48:40.789Z",
          finish: true,
          finishAt: "2025-10-13T10:48:40.789Z",
          cleaning_cancelled: false,
          cleaning_cancelled_at: null,
          battery_dead: false,
          battery_dead_at: null,
          battery_health_status: "✅ Battery is healthy!",
          battery_health_status_updated_at: "2025-10-13T10:53:40.800Z",
          forward_cleaning_time: null,
          forward_cleaning_time_received_at: null,
          reverse_cleaning_time: null,
          reverse_cleaning_time_received_at: null,
          total_cleaning_time: null,
          total_cleaning_time_received_at: null,
          battery_before_cleaning: null,
          battery_before_cleaning_received_at: null,
          battery_at_reverse_station: null,
          battery_at_reverse_station_received_at: null,
          battery_after_cleaning: null,
          battery_after_cleaning_received_at: null,
          temperature_before_cleaning: null,
          temperature_before_cleaning_received_at: null,
          temperature_at_reverse_station: null,
          temperature_at_reverse_station_received_at: null,
          temperature_after_cleaning: null,
          temperature_after_cleaning_received_at: null,
          cycle_average_brush_current: null,
          cycle_average_brush_current_received_at: null,
          cycle_average_wheel_current: null,
          cycle_average_wheel_current_received_at: null,
          cycle_max_wheel_current: null,
          cycle_max_wheel_current_received_at: null,
          cycle_max_brush_current: null,
          cycle_max_brush_current_received_at: null,
          cycle_count: null,
          cycle_count_received_at: null,
          cleaning_mertic: false,
          cleaning_metric_recievet_at: null,
        },
        track_details: [
          {
            point: 20,
            timestamp: "2025-10-13T10:49:10.824Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 21,
            timestamp: "2025-10-13T10:49:40.841Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 22,
            timestamp: "2025-10-13T10:50:22.810Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 23,
            timestamp: "2025-10-13T10:50:52.881Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 24,
            timestamp: "2025-10-13T10:51:22.843Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 25,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 26,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 27,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 28,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 29,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 30,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 31,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 32,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 33,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 34,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 35,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 36,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 37,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 38,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 39,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
          {
            point: 40,
            timestamp: "2025-10-13T10:51:40.996Z",
            reached_to_next_point: false,
            next_point: null,
          },
        ],
        last_activity: [
          {
            timestamp: "2025-10-13T10:51:40.996Z",
            data: "19",
            topic: "Uplink Received",
            details:
              "19 uplink received from robot and robot is ready to clean",
          },
        ],
      },
    ],

    // Robot details with cleaning info
    robot: {
      robot_no: "Robot-13-V4",
      deveui: "2CF7F120634001AA",
      _id: "6710A4F2B1239AF9D0E2",
      block: "Block-A1",
      lora_no: "14",
      old_lora: "12",
      site_id: "solar_farm_alhabad",
    },
  },
];
