export const roles = [
  {
    role: 'Master Admin',
    permissions: [
      {
        id: 'P001',
        description: 'CRUD operations for all users',
        type: 'CRUD',
      },
      {
        id: 'P002',
        description: 'Monitor system activities and logs',
        type: 'Read',
      },
      { id: 'P003', description: 'Manage application settings', type: 'CRUD' },
      { id: 'P004', description: 'Oversee all sites and robots', type: 'CRUD' },
      {
        id: 'P005',
        description: 'Access analytics, reports, and trends',
        type: 'CRUD',
      },
      {
        id: 'P006',
        description: 'Assign projects to project engineers',
        type: 'CRUD',
      },
      { id: 'P007', description: 'Shift robots within sites', type: 'Update' },
    ],
  },
  {
    role: 'Project Engineer',
    permissions: [
      {
        id: 'P008',
        description: 'View and manage assigned sites and robots',
        type: 'CRUD',
      },
      { id: 'P009', description: 'Commission robots', type: 'CRUD' },
      { id: 'P010', description: 'Oversee service operations', type: 'CRUD' },
      {
        id: 'P011',
        description: 'Analyze trends for robot failures',
        type: 'Read',
      },
      { id: 'P012', description: 'Send notifications', type: 'Create' },
    ],
  },
  {
    role: 'Service Admin',
    permissions: [
      {
        id: 'P013',
        description: 'Assign and resolve service tickets',
        type: 'CRUD',
      },
      { id: 'P014', description: 'Monitor robot health scores', type: 'Read' },
      {
        id: 'P015',
        description: 'Analyze trends for service issues',
        type: 'Read',
      },
    ],
  },
  {
    role: 'Site Technician',
    permissions: [
      { id: 'P016', description: 'Handle daily operations', type: 'CRUD' },
      { id: 'P017', description: 'Execute robot commands', type: 'Update' },
      {
        id: 'P018',
        description: 'Generate and submit cleaning reports',
        type: 'Create',
      },
    ],
  },
  {
    role: 'Client Admin',
    permissions: [
      {
        id: 'P019',
        description: 'Manage company sites and users',
        type: 'CRUD',
      },
      {
        id: 'P020',
        description: 'Download reports for all sites',
        type: 'Read',
      },
      {
        id: 'P021',
        description: 'Raise tickets for technical issues',
        type: 'Create',
      },
    ],
  },
  {
    role: 'Client Technician',
    permissions: [
      { id: 'P022', description: 'Perform robot operations', type: 'Update' },
      { id: 'P023', description: 'Monitor robot status', type: 'Read' },
      { id: 'P024', description: 'Perform site-specific tasks', type: 'CRUD' },
    ],
  },
];

export const users = [
  {
    username: 'Vaibhav Randale',
    email: 'vaibhav.r@taypro.in',
    password: '123456789',
    role: 'Master Admin',
  },
  {
    username: 'Jitesh Kute',
    email: 'jitesh.kute@taypro.in',
    password: 'projects123',
    role: 'Project Engineer',
  },
  {
    username: 'Abhay Singh',
    email: 'abhay.singh@taypro.in',
    password: 'service123',
    role: 'Service Admin',
  },
  {
    username: 'Arjun Rathod',
    email: 'arjun.rathod@taypro.in',
    password: 'tech123',
    role: 'Site Technician',
  },
  {
    username: 'Dhiren Bhatt',
    email: 'dhiren@gmail.com',
    password: 'dhiren23',
    role: 'Client Admin',
  },
  {
    username: 'ABD DEF',
    email: 'abc@gmail.com',
    password: 'client23',
    role: 'Client Technician',
  },
];
export const sites = [
  {
    id: 1,
    siteName: 'Avaada Clean Projects',
    location: 'Agar, MP',
    site_id: 'avaada_clean_projects_agar_mp',
  },
  {
    id: 2,
    siteName: 'ReNew Power',
    location: 'Bikaner, RJ',
    site_id: 'renew_power_bikaner_rj',
  },
  {
    id: 3,
    siteName: 'Adani Green Energy',
    location: 'Jaisalmer, RJ',
    site_id: 'adani_green_energy_jaisalmer_rj',
  },
  {
    id: 4,
    siteName: 'Tata Power Solar',
    location: 'Nellore, AP',
    site_id: 'tata_power_solar_nellore_ap',
  },
  {
    id: 5,
    siteName: 'Azure Power',
    location: 'Kurnool, AP',
    site_id: 'azure_power_kurnool_ap',
  },
  {
    id: 6,
    siteName: 'ACME Solar',
    location: 'Khadoda, GJ',
    site_id: 'acme_solar_khadoda_gj',
  },
  {
    id: 7,
    siteName: 'Mahindra Susten',
    location: 'Rajasthan, RJ',
    site_id: 'mahindra_susten_rajasthan_rj',
  },
  {
    id: 8,
    siteName: 'NHPC Solar Project',
    location: 'Leh, Ladakh',
    site_id: 'nhpc_solar_project_leh_ladakh',
  },
  {
    id: 9,
    siteName: 'Hero Future Energies',
    location: 'Tumkur, KA',
    site_id: 'hero_future_energies_tumkur_ka',
  },
  {
    id: 10,
    siteName: 'SJVN Solar Park',
    location: 'Baghpat, UP',
    site_id: 'sjvn_solar_park_baghpat_up',
  },
  {
    id: 11,
    siteName: 'JSW Energy Solar',
    location: 'Nagpur, MH',
    site_id: 'jsw_energy_solar_nagpur_mh',
  },
  {
    id: 12,
    siteName: 'Hindustan Power',
    location: 'Anantapur, AP',
    site_id: 'hindustan_power_anantapur_ap',
  },
  {
    id: 13,
    siteName: 'NTPC Solar Plant',
    location: 'Ramagundam, TG',
    site_id: 'ntpc_solar_plant_ramagundam_tg',
  },
  {
    id: 14,
    siteName: 'Sterling & Wilson Solar',
    location: 'Bhuj, GJ',
    site_id: 'sterling_wilson_solar_bhuj_gj',
  },
  {
    id: 15,
    siteName: 'Engie Solar Park',
    location: 'Kadapa, AP',
    site_id: 'engie_solar_park_kadapa_ap',
  },
  {
    id: 16,
    siteName: 'ACB India Solar',
    location: 'Raipur, CG',
    site_id: 'acb_india_solar_raipur_cg',
  },
  {
    id: 17,
    siteName: 'SB Energy',
    location: 'Phalodi, RJ',
    site_id: 'sb_energy_phalodi_rj',
  },
  {
    id: 18,
    siteName: 'Jakson Solar',
    location: 'Bareilly, UP',
    site_id: 'jakson_solar_bareilly_up',
  },
  {
    id: 19,
    siteName: 'SunSource Energy',
    location: 'Noida, UP',
    site_id: 'sunsource_energy_noida_up',
  },
  {
    id: 20,
    siteName: 'Essel Green Energy',
    location: 'Rewa, MP',
    site_id: 'essel_green_energy_rewa_mp',
  },
];

export const robots = [
  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 0,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },

  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 0,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526112 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60790',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526113 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60791',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'AAG-2526114 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60792',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526115 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60793',
    block: 'Block-3',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ADM-2526111 (adani_mumbai)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'RNW-9876543 (renew_bikaner)',
    deveui: 'B9C8D7E6F5A40321',
    block: 'Block-2',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 13:15:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'TPW-6523451 (tata_nellore)',
    deveui: 'C1D2E3F4A5B60789',
    block: 'Block-3',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 12:45:00',
    lora_state: 0,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AZP-6543211 (azure_kurnool)',
    deveui: 'D9E8F7A6B5C40321',
    block: 'Block-4',
    site_id: 'azure_power_kurnool_ap',
    company: 'Azure Power',
    last_update: '2025-01-30 11:30:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ACM-1234987 (acme_khadoda)',
    deveui: 'E1F2A3B4C5D60789',
    block: 'Block-5',
    site_id: 'acme_solar_khadoda_gj',
    company: 'ACME Solar',
    last_update: '2025-01-30 10:50:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'MHS-6547890 (mahindra_rajasthan)',
    deveui: 'F9A8B7C6D5E40321',
    block: 'Block-6',
    site_id: 'mahindra_susten_rajasthan_rj',
    company: 'Mahindra Susten',
    last_update: '2025-01-30 10:15:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'NHPC-8765432 (nhpc_leh)',
    deveui: 'A1B2C3D4E5F60987',
    block: 'Block-7',
    site_id: 'nhpc_solar_project_leh_ladakh',
    company: 'NHPC Solar Project',
    last_update: '2025-01-30 09:40:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'HFE-4526789 (hero_tumkur)',
    deveui: 'B9C8D7E6F5A40123',
    block: 'Block-8',
    site_id: 'hero_future_energies_tumkur_ka',
    company: 'Hero Future Energies',
    last_update: '2025-01-30 08:55:00',
    lora_state: 0,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'SJVN-1592634 (sjvn_baghpat)',
    deveui: 'C1D2E3F4A5B60987',
    block: 'Block-9',
    site_id: 'sjvn_solar_park_baghpat_up',
    company: 'SJVN Solar Park',
    last_update: '2025-01-30 08:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'JSW-5647382 (jsw_nagpur)',
    deveui: 'D9E8F7A6B5C40123',
    block: 'Block-10',
    site_id: 'jsw_energy_solar_nagpur_mh',
    company: 'JSW Energy Solar',
    last_update: '2025-01-30 07:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'HND-7854962 (hindustan_anantapur)',
    deveui: 'E1F2A3B4C5D60987',
    block: 'Block-1',
    site_id: 'hindustan_power_anantapur_ap',
    company: 'Hindustan Power',
    last_update: '2025-01-30 07:15:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'NTPC-9867432 (ntpc_ramagundam)',
    deveui: 'F9A8B7C6D5E40123',
    block: 'Block-2',
    site_id: 'ntpc_solar_plant_ramagundam_tg',
    company: 'NTPC Solar Plant',
    last_update: '2025-01-30 06:45:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'SW-9874532 (sterling_bhuj)',
    deveui: 'A1B2C3D4E5F60976',
    block: 'Block-3',
    site_id: 'sterling_wilson_solar_bhuj_gj',
    company: 'Sterling & Wilson Solar',
    last_update: '2025-01-30 06:10:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ENG-4532981 (engie_kadapa)',
    deveui: 'B9C8D7E6F5A40987',
    block: 'Block-4',
    site_id: 'engie_solar_park_kadapa_ap',
    company: 'Engie Solar Park',
    last_update: '2025-01-30 05:30:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ACB-9674521 (acb_raipur)',
    deveui: 'C1D2E3F4A5B60976',
    block: 'Block-5',
    site_id: 'acb_india_solar_raipur_cg',
    company: 'ACB India Solar',
    last_update: '2025-01-30 05:00:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'SBE-4678213 (sb_phalodi)',
    deveui: 'D9E8F7A6B5C40198',
    block: 'Block-6',
    site_id: 'sb_energy_phalodi_rj',
    company: 'SB Energy',
    last_update: '2025-01-30 04:45:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'JKS-7654892 (jakson_bareilly)',
    deveui: 'E1F2A3B4C5D60912',
    block: 'Block-7',
    site_id: 'jakson_solar_bareilly_up',
    company: 'Jakson Solar',
    last_update: '2025-01-30 04:20:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'SSE-5432918 (sunsource_noida)',
    deveui: 'F9A8B7C6D5E40156',
    block: 'Block-8',
    site_id: 'sunsource_energy_noida_up',
    company: 'SunSource Energy',
    last_update: '2025-01-30 03:55:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'EGE-7654321 (essel_rewa)',
    deveui: 'A1B2C3D4E5F60943',
    block: 'Block-9',
    site_id: 'essel_green_energy_rewa_mp',
    company: 'Essel Green Energy',
    last_update: '2025-01-30 03:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },

  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526112 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60790',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526113 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60791',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'AAG-2526114 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60792',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526115 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60793',
    block: 'Block-3',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },

  // Site 2: Adani Green Energy (Jaisalmer, RJ)
  {
    robot_no: 'ADM-2526111 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60789',
    block: 'Block-1',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ADM-2526112 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60790',
    block: 'Block-1',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ADM-2526113 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60791',
    block: 'Block-2',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ADM-2526114 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60792',
    block: 'Block-2',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ADM-2526115 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60793',
    block: 'Block-3',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },

  // Site 3: ReNew Power (Bikaner, RJ)
  {
    robot_no: 'RNW-9876541 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60789',
    block: 'Block-1',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'RNW-9876542 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60790',
    block: 'Block-1',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'RNW-9876543 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60791',
    block: 'Block-2',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'RNW-9876544 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60792',
    block: 'Block-2',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'RNW-9876545 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60793',
    block: 'Block-3',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },

  // Site 4: Tata Power Solar (Nellore, AP)
  {
    robot_no: 'TPW-6523451 (tata_nellore)',
    deveui: 'D1E2F3G4H5I60789',
    block: 'Block-1',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'TPW-6523452 (tata_nellore)',
    deveui: 'D1E2F3G4H5I60790',
    block: 'Block-1',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'TPW-6523453 (tata_nellore)',
    deveui: 'D1E2F3G4H5I60791',
    block: 'Block-2',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'TPW-6523454 (tata_nellore)',
    deveui: 'D1E2F3G4H5I60792',
    block: 'Block-2',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'TPW-6523455 (tata_nellore)',
    deveui: 'D1E2F3G4H5I60793',
    block: 'Block-3',
    site_id: 'tata_power_solar_nellore_ap',
    company: 'Tata Power Solar',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },

  {
    robot_no: 'AAG-2526111 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60789',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'AAG-2526112 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60790',
    block: 'Block-1',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'AAG-2526113 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60791',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'At Dock',
  },
  {
    robot_no: 'AAG-2526114 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60792',
    block: 'Block-2',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'AAG-2526115 (avaada_agar)',
    deveui: 'A1B2C3D4E5F60793',
    block: 'Block-3',
    site_id: 'avaada_clean_projects_agar_mp',
    company: 'Avaada Clean Projects',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ADM-2526111 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60789',
    block: 'Block-1',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ADM-2526112 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60790',
    block: 'Block-1',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'ADM-2526113 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60791',
    block: 'Block-2',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'At Dock',
  },
  {
    robot_no: 'ADM-2526114 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60792',
    block: 'Block-2',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'ADM-2526115 (adani_jaisalmer)',
    deveui: 'B1C2D3E4F5G60793',
    block: 'Block-3',
    site_id: 'adani_green_energy_jaisalmer_rj',
    company: 'Adani Green Energy',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'RNW-9876541 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60789',
    block: 'Block-1',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:30:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'RNW-9876542 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60790',
    block: 'Block-1',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:35:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
  {
    robot_no: 'RNW-9876543 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60791',
    block: 'Block-2',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:40:00',
    lora_state: 1,
    last_status: 'At Dock',
  },
  {
    robot_no: 'RNW-9876544 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60792',
    block: 'Block-2',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:45:00',
    lora_state: 1,
    last_status: 'Cleaning Finished',
  },
  {
    robot_no: 'RNW-9876545 (renew_bikaner)',
    deveui: 'C1D2E3F4G5H60793',
    block: 'Block-3',
    site_id: 'renew_power_bikaner_rj',
    company: 'ReNew Power',
    last_update: '2025-01-30 14:50:00',
    lora_state: 1,
    last_status: 'Cleaning Started',
  },
];
