name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy
      run: |
        cd /var/www/taypro-console-frontend
        git pull
        npm install
        npm run build
        echo "Frontend updated at $(date)" | msmtp yogesh@taypro.in
